# Generated by Django 5.2.7 on 2025-10-31 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Venda',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='historico_compras',
        ),
    ]
