# Generated by Django 5.2.7 on 2025-11-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_pedido_venda_remove_cliente_historico_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
